// <auto-generated />
using System;
using CleanArquitecture.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArquitecture.Infra.Data.Migrations
{
    [DbContext(typeof(TaxeriaDbContext))]
    partial class TaxeriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArquitecture.Domain.Models.Carro", b =>
                {
                    b.Property<int>("Id_Carro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Carro");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("CleanArquitecture.Domain.Models.CarroChofer", b =>
                {
                    b.Property<DateTime>("DateTakeCarro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CarroId_Carro")
                        .HasColumnType("int");

                    b.Property<int?>("ChoferId")
                        .HasColumnType("int");

                    b.HasKey("DateTakeCarro");

                    b.HasIndex("CarroId_Carro");

                    b.HasIndex("ChoferId");

                    b.ToTable("Taxistas");
                });

            modelBuilder.Entity("CleanArquitecture.Domain.Models.Chofer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Licencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Choferes");
                });

            modelBuilder.Entity("CleanArquitecture.Domain.Models.CarroChofer", b =>
                {
                    b.HasOne("CleanArquitecture.Domain.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroId_Carro");

                    b.HasOne("CleanArquitecture.Domain.Models.Chofer", "Chofer")
                        .WithMany()
                        .HasForeignKey("ChoferId");
                });
#pragma warning restore 612, 618
        }
    }
}
